Review_past_project
OLIPLICHE/review_my_past_project pull request #1
Opened 2021-07-07 17:59 UTC by OLIPLICHE

I am requesting to review my past project

2021-07-07 20:54 UTC, de-scholar requested changes
Hello Paka Mavoungou Paka, thank you for submitting this review request, however I am marking it because I couldn't find any review you made, kindly review your past project and submit a review request again

2021-07-07 22:09 UTC, OLIPLICHE commented on index.html
> +             </a>
Delete the blanc lines inside your block.

2021-07-07 22:35 UTC, OLIPLICHE reviewed
# Changes required
Go through my comment below and make all required changes. Please submit for review when you are done.
Thank you.

2021-07-07 22:35 UTC, OLIPLICHE commented on README.md
> +
There is too much blank line within sections. do not add blank lines, spaces without a reason. I advise you to clean the blank lines to make your work looks more professional.
Thank you.

2021-07-07 22:35 UTC, OLIPLICHE commented on style.css
> +
Delete blank lines.

2021-07-07 22:35 UTC, OLIPLICHE commented on index.html
> +        </nav>
For readability, add two spaces indentation, and do not use the tab key.

2021-07-08 01:04 UTC, MahmoudBakr23 requested changes
Hello @OLIPLICHE 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Nice job addressing the issues.
- Well done providing why you asked for this request.

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️

- [ ] Good job addressing the issues and why you requested them. However, I think it'd be better if you used more kind words and fewer orders.
_This is a polite suggestion: "I think it would be better to use semantic tags"
This reads like an order: "Use semantic tags"_

- [ ] Your review summary is too short, it'd be nicer if you tried to make it more detailed.
_You should write at least 2 comments in the review._

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Kindly consider using emojis in your comments. It helps to make it friendly and kind 🙏 🥰 

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 01:04 UTC, MahmoudBakr23 commented on index.html
> +
- [ ] As an example to my review comments above ⏫

**Instead** of "Delete the blank lines inside your block.", You can write something like:

Kindly always keep in mind to remove the extra blank lines or indentations to maintain your code clean and the site optimized.

>You can read about this tip and more at this [link](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2021-07-08 02:28 UTC, OLIPLICHE reviewed
you did a nice job, 👍 and keep it up. I want you to add something to your code to make your work perfect.
Please check my comments under the review to make small changes.♻️

Kindly send me a message if you have any questions.

2021-07-08 02:41 UTC, MahmoudBakr23 approved these changes
Hi @OLIPLICHE 😃, 

Good job with the requested changes. 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 02:52 UTC, merged